const $ = (s) => document.querySelector(s);
const form = $('#applicationForm'); const inputFiles = $('#files'); const fileList = $('#fileList');
let files = [];
const allowed = ['pdf','doc','docx','xls','xlsx','jpg','jpeg','png'];
const showError = (input, message) => { const field = input.closest('.field'); if (!field) return; field.classList.toggle('invalid', !!message); field.querySelector('.error').textContent = message || ''; };
function validateFiles(list) { const error = $('#fileError'); if (!list.length) return error.textContent = 'Добавьте хотя бы один файл.', false; if(list.length > 3) return error.textContent = 'Можно загрузить не более 3 файлов.', false; if([...list].some(f => f.size > 20 * 1024 * 1024 || !allowed.includes(f.name.split('.').pop().toLowerCase()))) return error.textContent = 'Один из файлов имеет недопустимый тип или превышает 20 МБ.', false; error.textContent = ''; return true; }
function renderFiles() { fileList.innerHTML = files.map((f,i) => `<div class="file"><span>↗</span><div><b>${f.name}</b><small>${(f.size/1024/1024).toFixed(1)} МБ</small></div><button type="button" data-file="${i}" aria-label="Удалить файл">×</button></div>`).join(''); }
inputFiles.addEventListener('change', () => { files = [...inputFiles.files]; validateFiles(files); renderFiles(); });
fileList.addEventListener('click', e => { const i=e.target.dataset.file; if(i !== undefined) { files.splice(i,1); renderFiles(); validateFiles(files); }});
$('#dropzone').addEventListener('dragover', e => {e.preventDefault(); $('#dropzone').classList.add('drag');});
$('#dropzone').addEventListener('dragleave', () => $('#dropzone').classList.remove('drag'));
$('#dropzone').addEventListener('drop', e => {e.preventDefault(); $('#dropzone').classList.remove('drag'); files=[...e.dataTransfer.files]; validateFiles(files); renderFiles();});
$('#phone').addEventListener('input', e => { let d=e.target.value.replace(/\D/g,''); if(d.startsWith('8')) d='7'+d.slice(1); if(!d.startsWith('7') && d) d='7'+d; d=d.slice(0,11); let x=d.slice(1); e.target.value = d ? '+7' + (x.length ? ' ('+x.slice(0,3) : '') + (x.length>3 ? ') '+x.slice(3,6) : '') + (x.length>6 ? '-'+x.slice(6,8) : '') + (x.length>8 ? '-'+x.slice(8,10) : '') : ''; });
form.addEventListener('submit', e => { e.preventDefault(); let valid=true; const required=[['event','Выберите мероприятие.'],['company','Укажите организацию.'],['lastName','Укажите фамилию.'],['firstName','Укажите имя.']]; required.forEach(([id,msg])=>{const el=$('#'+id); const bad=!el.value.trim(); showError(el,bad?msg:'');valid&&=!bad}); const email=$('#email'), phone=$('#phone'); const emailBad=!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email.value);showError(email,emailBad?'Введите корректный email.':'');valid&&=!emailBad; const phoneBad=phone.value.replace(/\D/g,'').length!==11;showError(phone,phoneBad?'Введите номер полностью.':'');valid&&=!phoneBad; valid = validateFiles(files) && valid; if(!$('#consent').checked){$('.consent').classList.add('consent-error');valid=false}else $('.consent').classList.remove('consent-error'); if(!valid) return; const btn=form.querySelector('.submit'); btn.disabled=true; btn.querySelector('span').textContent='Сохраняем…'; setTimeout(()=>{ $('#applicationNumber').textContent = new Date().toISOString().slice(0,10)+'-'+String(Math.floor(Math.random()*9000)+1000); $('#successModal').classList.add('visible'); $('#successModal').setAttribute('aria-hidden','false'); btn.disabled=false; btn.querySelector('span').textContent='Сохранить'; },700);});
function toggleModal(id, show) { const m=$('#'+id); m.classList.toggle('visible',show);m.setAttribute('aria-hidden',!show); }
$('#openAdmin').addEventListener('click',()=>toggleModal('adminModal',true)); $('#closeAdmin').addEventListener('click',()=>toggleModal('adminModal',false)); document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>toggleModal(b.dataset.close,false)));
